browser:
  browser_name: 'chromium' # 浏览器内核
  headless: true # 无头模式
  slow_mo: 10 # 延迟执行
  downloads_path: null # 下载地址
context:
  ignore_https_errors: true # 忽略 https 错误
  java_script_enabled: true # 允许脚本执行
  bypass_csp: false # 安全策略
  viewport: # 窗口大小
    width: 1920
    height: 1080
  locale: 'zh-CN' # 语言设置
  extra_http_headers: null # 浏览器头
  record_video_dir: 'reports' # 录屏地址

hook: 'hook.py'
